version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always
    volumes:
      - ./sites.json:/app/sites.json
      - ./metrics.json:/app/metrics.json
      - ./uptime.json:/app/uptime.json

  scheduler:
    build: .
    command: python scheduler.py
    env_file:
      - .env
    restart: always
    volumes:
      - ./sites.json:/app/sites.json
      - ./metrics.json:/app/metrics.json
      - ./uptime.json:/app/uptime.json